name: Update Script File

on:
  push:
    branches:
      - main
    paths:
      - 'script/**.js'

jobs:
  update-version-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Read versions and update JSON
        run: node .github/scripts/update-version.js

      - name: Commit and push if necessary
        run: |
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          git add script/versions.json
          git commit -m "Update script versions file" -a || echo "No changes to commit"
          git push
  sync_to_oss:
    needs: update-version-json
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install ossutil
        run: |
          wget http://gosspublic.alicdn.com/ossutil/1.7.0/ossutil64
          chmod 755 ossutil64

      - name: Config ossutil
        env:
          OSS_ENDPOINT: 'oss-cn-beijing.aliyuncs.com'
          OSS_ACCESS_KEY_ID: ${{ secrets.OSS_ACCESS_KEY_ID }}
          OSS_ACCESS_KEY_SECRET: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
        run: |
          ./ossutil64 config -e $OSS_ENDPOINT -i $OSS_ACCESS_KEY_ID -k $OSS_ACCESS_KEY_SECRET

      - name: Sync files to OSS
        env:
          OSS_BUCKET: 'aowuucdn'
        run: |
          ./ossutil64 sync -u -f ./script/ oss://$OSS_BUCKET/script/
